version: 2.1
jobs:
  blog_demo_deployment_process:
    docker:
      - image: cimg/node:19.8.1
        auth: 
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD

    steps:
      - checkout
      
      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: npm update
          command: sudo npm install -g npm@latest
      
      - run:
          name: install jest
          command: sudo npm install --save-dev jest ts-jest
      - run:
          name: run automated tests
          command: npm test
      
      - run:
          name: Build and Push Docker Image
          command: |
            docker build -t $DOCKERHUB_USERNAME/blog-demo:latest .
            docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD docker.io
            docker push $DOCKERHUB_USERNAME/blog-demo:latest


workflows:
  blog-demo: 
    jobs:
      - blog_demo_deployment_process:
          context: DOCKERHUB_AUTH